permalink:           pretty

# Setup
title:               Welcome To Museop's Blog~!
tagline:             ''
description:         'This Blog is using my study.'
url:                 http://museop.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Kim Museop
  url:               
  email:             kms920806@naver.com

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
paginate_path: "page:num"

markdown: kramdown
mathjax: true
