

# Setup
title:               Pleasure of learning
tagline:             ''
description:         'This Blog is using my study.'
url:                 http://museop.github.io
baseurl:             ''
paginate:            4

# About/contact
author:
  name:              Kim Museop
  url:               
  email:             kms920806@naver.com

# Custom vars
version:             1.0.1

gems: [jekyll-paginate]
paginate_path: "page:num"

markdown: kramdown

math: true

disqus_shortname: museop

